### ISSUE TITLE
esp8266 接続できず

### ISSUE THREAD

**Issue by ohisama** [shiguredo/sango-help#1]
sango ライトプランをohisama@githubで
利用させていただいてます。
esp8266という、モジュールから接続しようと
していますが、5秒でclosedされます。
ログから、対策を推察できませんか。

コマンドは、以下です。
AT＋CIPSTART="TCP","125.0.127.190",1883
レスポンスは、以下です。
CONNECT

OK
CLOSED

**Comment by shirou** [comment]
TCP CONNECTから5秒以内にMQTT CONNECTをしなければ、自動的にTCP CLOSEされるようになっています。

**Comment by ohisama** [comment]
お世話様です。5秒以内に接続するようにして、接続できました。
もう一つ問題が、（仕様かも知れませんが）
TCPからpublishして、ｗｓからsubscribeできません。
TCPに接続していて、ｗｓに接続すると、TCPが切られます。
ｗｓに接続していて、TCPに接続すると、ｗｓが切られます。
ご指導願います。

**Comment by shirou** [comment]
同じClientIDを使っていないでしょうか。
MQTTの仕様で、同じClientaIDで接続しようとすると、後の接続が生き、前の接続が切断されます。
ClientID自体の仕様はありませんので、ランダムな文字列でも構いません。

**Comment by ohisama** [comment]
はい、同じClientIDを使ってました。TCPからpublishして、ｗｓからsubscribeできました。ありがとうございます。

**Comment by shirou** [comment]
良かったです。このIssueはCloseします。

もしもまた問題が起きましたら、再度Openするか、別Issueを作成してください。
よろしくお願いします。
