### ISSUE TITLE
メッセージ数について

### ISSUE THREAD

**Issue by hotchpotch** [shiguredo/sango-help#10]
こちら、表示されているメッセージ数は何を起点にカウントされてますでしょうか？

というのも、subscriber のみを接続している(と思ってる)状態でも、数秒に1づつカウントアップされており、publish でのデータ送信以外にも keepalive の ping などをメッセージ数をカウントしてるのかと思いまして、教えていただけると助かります。

**Comment by shirou** [comment]
仰るとおり、MQTTは疎通確認のために [Keep Alive](http://docs.oasis-open.org/mqtt/mqtt/v3.1.1/os/mqtt-v3.1.1-os.html#_Toc385349238) メッセージを送っています。Sangoでの表示メッセージ数にはこのKeep Aliveも含んでおりますので、データをpublishで送っていない状態でも、connectionが維持されている限り、カウントアップされております。

**Comment by hotchpotch** [comment]
@shirou 

早速のご回答ありがとうございます。カウントアップの挙動、理解できました。
