### ISSUE TITLE
QoS 2

### ISSUE THREAD

**Issue by kojo1** [shiguredo/sango-help#2]
はじめまして。wolfSSL古城と申します。

mbedからstd1.mqtt.shiguredo.jpにMQTT接続の簡単なテストをしています。
QoS0、1までのPub/Subは成功しているようなのですが、QoS2ではPub後にSubメッセージが届かず、
サーバ側からはTCPディスコネクト（FIN, ACK）されているように見えます。
原因として考えられそうな要因、解析方法などご教示いただけないでしょうか。

よろしくお願いします。

古城

**Comment by shirou** [comment]
お問い合わせありがとうございます。 「QoS2ではPub後にSubメッセージが届かず」とのことですが、
「Pub後に同一クライアントがSubメッセージを送るが、SubAckメッセージは受け取れずにTCP Disconnectされる」ということでしょうか。つまり、Publishはできている、という理解です。
その場合、
1. PubもSubもQoSは2でしょうか
2. 最初に送ったPubメッセージは他のクライアントでSubできていますでしょうか。
3. Pub -> Subではなく、Subのみはできますでしょうか。

**Comment by kojo1** [comment]
お世話身なります。説明が不正確ですみません。

テストは物理的に１枚のクライアント・ボードで行っています。
まず、QoS2でSubしたあとに、QoS0, 1, 2と順番に１回ずつPubするようになっています。
このロジックで、QoS0と1の直後にそれぞれSubメッセージが返ってくることは
確認できました。

QoS2の場合、PubのあとにSub側にQoS2のメッセージが返らず、
なぜかQoS1のPubしたメッセージが再度返っているように見えます。
APIの戻り値的にはQoS2のPubは成功しているように見えます。
Wiresharkでも、QoS２のPubの後、サーバよりPSH,Ack、クライアントよりAckが返って
おり、やりとりは完結しているように見えます。

しかし、その後サーバから送られてくるメッセージはQoS1のPubメッセージの
ようです（Wireshark上も、クライアントプログラム的にも）。

なお、テストプログラム、MQTTのライブラリは下記に公開されているもので、
m2m.eclipse.orgに対するものをコネクトション情報のみ変更して使用しているため、
動作に関してこちらが誤解している面もあるかと思います。ご容赦ください。
とりあえず、m2m.eclipse.orgに対してはQoS0,1,2で動作するようです。

https://developer.mbed.org/teams/mqtt/code/HelloMQTT/

**Comment by shirou** [comment]
ありがとうございます。
ちょうど今 developer.mbed.org が落ちているので実際のコードを見れていませんが、
Disconnectはクライアント側が想定した動作ということですと、

- Subをしてから、  QoS0 -> QoS1 -> QoS2 の順番でPubをした時に、QoS2ではなく、なぜかQoS1のメッセージを受け取る
- すなわち、QoS1の同一メッセージを2回受け取れてしまう

ということが問題である、という理解です。QoS1の同一メッセージが二回受け取れるということは、リトライの問題なのではないか、と思われて調査をしています。

ただ、mbedでの検証は今すぐには難しいので、もしもよろしければWiresharkで関連するパケットだけを抽出したpcapファイルを頂けないでしょうか。

スタンダードプランの方は、 [sangoのダッシュボード](https://sango.shiguredo.jp/dashboard) の左メニューにメールでの連絡先が記載されていますので、そちらの方にメールして頂けると大変ありがたく思います。

よろしくお願いします。

**Comment by shirou** [comment]
頂いたpcapファイルを拝見したところ、

- QoS2だと思われていたメッセージは、QoS1の再送メッセージでした(DUPフラグが立っています)

  - サーバーからQoS1メッセージを受けた場合、クライアントがPubAckを送らないといけないのですが、クライアントがPubAckを送っていないため、サーバーが再送したのだと思います

- QoS2のメッセージはそもそもPublishが完了していない

  - Pubを送る -> PubReceieveを受け取った後に、クライアントがPubReleaseを送らないといけないのですが、送っていないようです。そのため、QoS2のメッセージ送信自体が完了していないように思われます

のではないか、と思います。

サンプルコードは、再送やQoSに関わらず、三つのメッセージを受け取ったら終了するため、 1. QoS0, 2. QoS1 3. QoS1の再送メッセージの三つを受け取って終わりになったのだと思います。

こちらでは、サンプル実装である、mosquittoをクライアントに使った場合には特に問題なくQoS2を送受信できました。
mbedのコードを読めてはいませんが、PubRelease はユーザがハンドリングしなくてはならないのかもしれません。

m2mではできる、というところが気になりますので、もう少しm2mを使って調査してみたいと思います。

**Comment by kojo1** [comment]
若山さん、

さっそくのご回答ありがとうございます。ご説明で、だいたいの動作理解できました。ようやくmbed環境が復旧したようなので、こちらもQoS2のみのSub/Pub
を実験してみました。添付の通り、shiguredo, m2m.eclipseともQoS2の
Subメッセージはかえっていないようです。ただし、なぜかm2mの場合、
プログラムの動作としてはSubメッセージのコールバックが動作して、
カラのメッセージを表示するという不可解な動作をしています。

ついでに、m2mのほうでもともとのプログラムの通りQoS0,1,2を発行した
場合のキャプチャも添付しました。この場合、なぜかQoS2のSubメッセージ
がかえっています。わたしはMQTTの詳細プロトコルまでは理解しておりません。
おそらく不完全なクライアントからのメッセージに対して、応答して
いるのだと思います。

いずれにしても、御社サーバ側よりmbedプログラム側の問題のようですので、
本家サイトのほうに質問をなげてみようかと思っています。週末の時間帯に
迅速な対応をいただき本当にありがとうございました。

ちなみに、このMQTTライブラリと弊社のTLSライブラリをつないで
MQTTSのほうも並行してテストさせていただいています。
本件と同根と思われる問題以外には特に問題なく、サーバ認証を含めて
動作しているようです。

https://developer.mbed.org/users/wolfSSL/code/HelloMQTTS/

今後共よろしくおねがいします。

古城


2015年8月2日 17:31 shirou <notifications@github.com>:

**Comment by shirou** [comment]
分かりにくくて申し訳ありません。こちらはGithubのIssueであり、メールではありません。そのため、添付ファイルが消えており、キャプチャ内容は分かりませんでした。

ですが、問題はsango側ではない、ということのようですので、このIssueはいったんcloseとさせて頂きます。

mbed側で問題が解決した、あるいはまた別の問題が発生した、ということであれば、このIssueをre-openして頂くか、別のIssueを作成して頂くようお願いします。もちろん、スタンダードプランの方ですので、直接メールでも構いません。

よろしくお願いします。
