### ISSUE TITLE
メッセージ数のサマリ表示が欲しい

### ISSUE THREAD

**Issue by mikosu3** [shiguredo/sango-help#3]
お世話なっております
ダッシュボードに日毎、週毎、月毎くらいで使用したメッセージ数のサマリ表示が欲しいです
月毎のメッセージ数に上限がありますので、指標となるものがあると先の見通しも立てやすいのではないかと思います

**Comment by voluntas** [comment]
@mikosu3 ご利用ありがとうございます。確かに欲しくなりますね ... 。毎日バッチ処理をしてデータを保存する感じになりそうです。すぐには難しそうですが、かなり前向きに検討させて頂きます。

**Comment by voluntas** [comment]
@mikosu3 社内で検討した結果、有償プラン限定でメッセージ数とコネクション数のサマリーを取っていくという方針になりました。開発とデプロイが終わり次第再度ご連絡します。

素晴らしい提案ありがとうございます。

**Comment by voluntas** [comment]
@mikosu3 メッセージ数のサマリ機能をデプロイしました。是非ご確認いただければ。

**Comment by mikosu3** [comment]
実装ありがとうございます。
使用率のパーセンテージ表示があるとなお良いかと思います。

**Comment by voluntas** [comment]
@mikosu3 確かに。色々と提案ありがとうございます。パーセンテージ表示も検討してみます。

**Comment by voluntas** [comment]
@mikosu3 使用率のパーセンテージを表示してみました。いかがでしょうか。

**Comment by mikosu3** [comment]
実装ありがとうございます。とても良いと思います！

**Comment by voluntas** [comment]
@mikosu3 ありがとうございます。今後も何か要望ありましたらお気軽にご連絡だください。
