### ISSUE TITLE
要望：MQTTSの証明書

### ISSUE THREAD

**Issue by j3tm0t0** [shiguredo/sango-help#4]
自己署名証明書じゃなくて、Valid な証明書を使用して頂けると助かります！

**Comment by voluntas** [comment]
要望ありがとうございます。ソラコム様の件だと思います。

独自証明書であまり困っていなかったのですが BEAM が間に入って確認されているんですね。

独自証明書用の CA を BEAM 側に登録できるような仕組みは今後ご検討されていますでしょうか。

もしされていない場合はこちらで認証局が発行したものを設定することを検討したいと思います。

**Comment by j3tm0t0** [comment]
類似機能としてAWS IoT接続を想定してクライアント証明書が利用出来るようになっているので、不可能ではないと思われます。

いずれにせよ、ユーザ側で特別な設定をせずとも接続出来る事が望ましいかと存じますので、認証局の発行した証明書をご検討頂けますと幸いです！

**Comment by voluntas** [comment]
@j3tm0t0 対応は未定とのことで了解いたしました。認証局発行証明書の導入を検討させていただこうと思います。

ただ、サーバ証明書の判断が完全にユーザコントロール外にあるというのはセキュリティ上よくないと考えておりますので、是非ユーザ側で証明書の追加をできるような仕組みを検討していただければと思います。
