### ISSUE TITLE
Pythonの「IOError: [Errno 32] Broken pipe」について、その他教えてください

### ISSUE THREAD

**Issue by TeruakiNakayama** [shiguredo/sango-help#5]
中山と申します。
sangoのLiteプランをテスト的に使わせていただいています。

【pythonプログラムのエラーについて】
raspberry piのpythonで永久ループさせてイベント発生時にpublishしていますが、数回publishが成功した後、よく「IOError: [Errno 32] Broken pipe」が出て、その後、publishができなくなり、プログラムを再起動すると回復します。
これは、なぜでしょうか。
接続時には発生しないで、しばらくするとサーバから切断されるようなので、「セッション有効期限」により、接続後30分で切断されるのでしょうか。それとも、最後のpublish後30分以上経過すると切断されるのでしょうか。それとも、別の原因でしょうか。
これを避ける標準的な方法はありますか。

【メッセージ数のカウントについて】
テスト環境が安定していないのではっきりしないのですが、「メッセージ数」のカウントはブローカにpublishしたメッセージの数(回数)でしょうか。その他にメッセージ数がカウントされることはありますか。

【メッセージの内容をWebページで確認する方法について】
メッセージの内容をWebページで確認する方法はありますか。
iOSのアプリでMQTTクライアントがありますが、面倒なので、PCでメッセージを確認したいです。

よろしくお願いいたします。

**Comment by shirou** [comment]
### 【pythonプログラムのエラーについて】

「セッション有効期限は」のMQTTのセッションであり、MQTT接続をサーバー側で覚えておく期限です。
30分でサーバー側から切断する、ということではありません。
raspberry piではなく、通常のPCを使い、安定したネットワーク回線を使った場合でも同様の問題が生じますでしょうか。
あるいは、 [mqttcli](https://github.com/shirou/mqttcli) を使った場合にはいかがでしょうか

また、paho-mqttには、 `reconnect()` メソッドがありますので、 `on_disconnect` 時に reconnectするように実装していただけると、自動的に再接続すると思います。


### 【メッセージ数のカウントについて】

メッセージ数はMQTTのメッセージすべてを数えております。MQTTは生存確認のメッセージを常にやりとりしていますので、
Publishしていなくても、接続しているならばメッセージ数は増えていきます。また、Subscribeなども同様にカウントされます。

### 【メッセージの内容をWebページで確認する方法について】

sangoでは、WebSocketを提供しておりますので、 [MQTT.js](https://github.com/mqttjs/MQTT.js) などを使うことで、
Webブラウザ上からメッセージを確認できます。
試すだけであれば、 [hivemqのデモ](http://www.hivemq.com/demos/websocket-client/ ) を試せます。

**Comment by TeruakiNakayama** [comment]
素早いご回答ありがとうございます。

【pythonプログラムのエラーについて】
サーバ側からの強制切断はないとのこと、了解しました。
それでは、30分で接続を忘れたサーバに対してpublishしたらどうなるでしょうか。
publishが失敗して、 on_disconnect  もなければ、パイプのエラーになってしまうのではないでしょうか。
これについては、 on_disconnect  等でキャッチして対策できるかやってみます。

【メッセージ数のカウントについて】
接続しているだけで、カウントアップすることもあるとのこと、了解しました。
これについて、Web上では書いてあるところが見つからなかったので、追加していただけるとうれしいです。

【メッセージの内容をWebページで確認する方法について】
hivemqのページ使ってみます。

ありがとうございました。

**Comment by voluntas** [comment]
@TeruakiNakayama メッセージ数のカウントの件、掲載しておきます、ご指摘ありがとうございます。

> それでは、30分で接続を忘れたサーバに対してpublishしたらどうなるでしょうか。
> publishが失敗して、 on_disconnect もなければ、パイプのエラーになってしまうのではないでしょうか。
> これについては、 on_disconnect 等でキャッチして対策できるかやってみます。
こちら、プログラム寄りの話でしたので、 sango サービスや MQTT プロトコルとしての視点から回答させて頂きます。

MQTT はクライアントが意図的に切断する、または何かが原因で通信が切れる意外は TCP のコネクションを張りっぱなしのプロトコルです。また内部で Ping/Pong もしておりキープアライブも実行されております。そのため、一度繋がった状態で、その後繋がらない場合はほとんどの場合でクライアント側の問題となります。

Python を使っているとのことでしたが、まずは mqttlcli でお試しいただけますでしょうか。

また、お問い合わせ頂くときは Python の MQTT クライアントのライブラリ名やバージョン、可能であれば使用したコードを提示したりして頂けると、推測での回答にならないため助かります。

また sango 以外の部分のサポートについて回答をご提供することは難しいことをご了承頂ければと思います。

**Comment by voluntas** [comment]
こちら、一ヶ月以上過ぎているためクローズさせて頂きます。もし何かありましたらまた issue をオープンしていただければと思います。
