### ISSUE TITLE
ブラウザ経由でのSubscriptionsについて

### ISSUE THREAD

**Issue by himuka** [shiguredo/sango-help#6]
初めまして、三反田と申します。
Liteプランを試験的に利用させて頂いており、重宝しています。
構成としては次の感じです。
パターン-1：
　Arduino uno　→　温度データを「publish]　→　Sangoへ　→　mosquitto clientで取得=>成功
パターン-2：　※Websocket利用
　Arduino uno　→　温度データを「publish]　→　Sangoへ　=>失敗
このパターン-2を実現してブラウザ表示を試行しているのですが、Arduino上のスケッチでWebsocket利用を
前提とした記述を試行しますが、Sangoへ接続できないです。
そこでご質問になります。
Q1:Websocketでのポート番号は？　8080？
Q2:ダッシュボード上で、WebSocket接続先    ws://lite.mqtt.shiguredo.jp/mqtt　となっておりますが
　　　サーバとして記述は、lite.mqtt.shiguredo.jp/mqtt　になりますか？
Q3:Hive-MQを利用して単純にデータを見ようとしますが、Sangoへの接続ができません。ここでもポート番号と　　　　サーバ部分の記述が？です。なお、usernae/password/topicはミスなく入れたのですが・・・
　　　ちなみにエラーは、Connect failed: AMQJS0007E Socket error:undefined　でした。

**Comment by shirou** [comment]
Q1: websocketのポートは80番となります。
Q2: 使用されるWebSocketのライブラリによって異なりますので、一概には言えません
Q3:  [こちらのデモ](http://www.hivemq.com/demos/websocket-client/) では

**Comment by himuka** [comment]
ご回答ありがとうございました。
Q2についてはもう少し深掘りしてみます。
Q3ですが、やはり接続ができませんでした。
エラー：Connect failed: AMQJS0006E Bad Connack return code:5 Connection Refused: not authorized.
が表示されました。ちなみに以下の通りに入力したのですが・・・
Host：lite.mqtt.shiguredo.jp
Post：80
ClientID：表示されていたまま
Username：himuka@github
Last-Will Topic：himuka@github/#

**Comment by shirou** [comment]
`Last-Will Topic：himuka@github/#` とされていますが、 Last-Will は異常切断時にpublishするためのものですので、 `#` は使えません。 `himuka@github/example` とする必要があります。

とりあえず問題の切り分けのために、LastWill関係はすべて入力しないで接続できるか確認してみてはいかがでしょうか

**Comment by himuka** [comment]
「LastWill関係はすべて入力しない」で接続が可能となりました。
お騒がせ致しました。

**Comment by shirou** [comment]
それは良かったです。Willもいろいろ試してみてください。このIssueはクローズします。またなにかございましたら新しいIssueを作成するか、このIssueを再度Openしてください。
