### ISSUE TITLE
ブラウザからSubするには

### ISSUE THREAD

**Issue by himuka** [shiguredo/sango-help#7]
三反田です。
初歩的な動作について教えて下さい。
ｓangoのliteプランで弊社のＡｒｄｕｉｎｏｰデバイスから、sangoへのpublishは
正常に稼働していて、linuxのmosquitto-clientからsubsは取得できます。

ブラウザからsubしたい場合は、以下のURLを参考にして接続で大丈夫かなと
考えてましたが如何でしょうか？
見ようみまねで、関連のjsファイル/index.htmlを自社内のlinuxサーバに配置して
自PCのブラウザを起動しましたが、画面上は接続エラー等も表示されず
真っ白画面でした。
https://sango.shiguredo.jp/docs/mqtt_javascript.html#javascript
もしかしたら、publishする際はwebsokect経由なのでしょうか？

**Comment by voluntas** [comment]
@himuka ご利用ありがとうございます。ブラウザからであれば MQTT over WebSocket のが良いかと思います。その際、認証などの設定もしていただければ、特に問題なく繋がると思います。

> もしかしたら、publishする際はwebsokect経由なのでしょうか？
こちらの質問の意図がくみ取れませんでしたので、想像で回答させて頂きます。

mqttws31.js は内部で WebSocket を使用しているため、問題ないと思います。
https://github.com/eclipse/paho.mqtt.javascript/blob/master/src/mqttws31.js#L979

**Comment by himuka** [comment]
三反田です。
レスありがとうございました。
以下のソースで試行しているのですが、画面には何も起こらずです。
firefoxの開発ツールのwebコンソールも同時に見てますがhttp 200 OK くらいしか表示されません。
javascript内で　alert表示させると、function以外では結果が返ります、
Sango側でのコネクション数も変わらないの、接続に行けてないような気がします。
何がマズイのでしょうか？
　※"mqttws31.jsファイルは、index2.htmlと同じディレクトリに配置済みです。
----------------------------------------------------------------------------------------------
<!DOCTYPE html>
<html>

  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <script src="mqttws31.js"></script>
<script>
// MQTTのクライアント
var client;

// ClientIDを指定
var clientId = "clientid-test";

// Sangoへの接続
function connect() {
    var user_name = "himuka@github";
    var pass = "**************";
    var wsurl = "ws://lite.mqtt.shiguredo.jp/mqtt";

    // WebSocketURLとClientIDからMQTT Clientを作成
    client = new Paho.MQTT.Client(wsurl, clientId);

    // 接続
    client.connect({userName: user_name, password: pass, onSuccess:onConnect, onFailure: failConnect});
}

// 接続失敗
function failConnect(e) {
    console.log("connect failed");
    console.log(e);
}

// 接続成功
function onConnect() {
    console.log("onConnect");
}
</script>
  </head>
  <body>
    <h1>MQTT sample</h1>
    <h2> List </h2>
	<div id="list"></div>
	<br />
  </body>
</html>

**Comment by voluntas** [comment]
@himuka 大変申し訳ありません。こちらでは MQTT 自体の技術的なサポートは残念ながらこちらでは行っておりません。

http://ja.stackoverflow.com/ などでご質問頂くのが良いかと思います。

**Comment by himuka** [comment]
了解致しました。
ありがとうございました。
