### ISSUE TITLE
接続で排他制御？

### ISSUE THREAD

**Issue by himuka** [shiguredo/sango-help#8]
MQTT+Anduinoで温度データを御社Sangoへpublish→自社でブラウザにてSubscribeまでは
正常に構築できて試験稼働しています。
ここに来て気付いたんですが、jsファイル内でclientId値を、ランダム値を自動生成して、接続を
行うと、最初に接続してデーﾀを受信してブラウザの動作が止まり、次に接続したブラウザのみが
データ受信の格好になってしまいます。1つのブラウザからしかデータ更新が見れません。
何か間違った記述でしょうか？MQTT接続情報で見ますと、publish側とブラウザで次の通りで
増加しませんでした。
コネクション数
2 / 10

**Comment by himuka** [comment]
すみません。
仕様をよく見ずに動作させていました。
--------------------------------------------------
Retain機能とは、トピックごとに最後にパブリッシュされたメッセージをMQTTサーバーが保持しておき、新しいサブスクライバーにそのメッセージを渡す機能です。MQTTは前述のとおり、パブリッシュ/サブスクライブ型モデルです。そのため、パブリッシュされた時にサブスクライブしていたクライアントにしかメッセージは送信されません。たとえば1時間ごとに更新される情報を得ようとサブスクライブしても、最長1時間はなにも情報が得られないことになります。しかし、この場合でもRetain機能を使うとその時点での最新の情報が得られます。
-----------------------------------------------------
もし、同時に見るにはRetain機能を実装しないとなんですね。

**Comment by shirou** [comment]
解決済みであれば、クローズしていただいてもよろしいでしょうか？
