### ISSUE TITLE
素人で　Subscribe　のやり方が理解できないのですが

### ISSUE THREAD

**Issue by sasaki1226** [shiguredo/sango-help#9]
MQTTでIotをやってみたくて
sango を見つけました。

当面ライトプランでやっているのですが、
素人のためいまいち理解ができません。

Arduinoを使用して、スマホのデザリングを利用して
sango に　Publish　し

それを　PCで　Subscribe　してデータを処理したい

と思ったいます。

ダッシュボードを見ると
メッセージ数がカウントされているので
何かはわかりませんがデータは送れたと思います。

しかし、そのデータを　PCに　Subscribe　したいのですが
思うようにいきません。

sango MQTTドキュメントを見ると
6つの言語の例がありますが
いまいち理解ができません。

サンプルプログラムを動かしてみたのですが
どれも思うように動作させられませんでした。

素人なので理解ができないようです。

一番やりやすい参考書等ありましたら教えて頂けないでしょうか

お願いします

**Comment by voluntas** [comment]
@sasaki1226 はじめまして。おそらくプログラミング経験はおありだとおもいますので、MQTT のクライアントの知識を増やすことが一番なのかなと思いました。私の方では残念ながら MQTT 関連のプログラミングが書かれているイイ参考書などの本は提示できそうにはないです。

ただ、 MQTT クライアントの Paho というライブラリのサイトが http://www.eclipse.org/paho/ とても情報がそろってると思います。

また、もし上手く動かないのであれば SO (http://ja.stackoverflow.com/) などでコードをはって質問してみるのが良いかもしれません。

こちらはあくまで sango のサポートのため MQTT クライアントなどのサポートには対応できず申し訳ありません。

**Comment by sasaki1226** [comment]
お忙しいところ

早々にありがとうございました
